[workspace]
members = [
    "chapter01-thread", "chapter02-threadpool", "chapter03-async", "chapter04-sync-primitives-01", "chapter05-sync-primitives-02", "chapter06-concurrency-set", "chapter07-process", "chapter08-channel", "chapter09-timer", "chapter13-tokio",
]
